# Generated by Django 3.1.5 on 2021-01-11 17:03

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.CharField(default='not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='expire:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 17, 3, 5, 802557, tzinfo=utc), verbose_name='date published'),
        ),
    ]
