# Generated by Django 3.1.5 on 2021-01-11 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210111_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text1',
            field=models.CharField(default='worked', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text2',
            field=models.CharField(default='not worked for me', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 17, 18, 42, 887155, tzinfo=utc), verbose_name='date published'),
        ),
    ]
