# Generated by Django 3.1.5 on 2021-01-11 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210111_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text1',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text2',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 22, 47, 46, 838129, tzinfo=utc), verbose_name='date published'),
        ),
    ]
