# Generated by Django 3.1.5 on 2021-01-12 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210112_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 10, 38, 19, 405780, tzinfo=utc), verbose_name='date published'),
        ),
    ]
